version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Allow empty password
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

 app-internship:
    depends_on:
      - mysqldb
    image: ameni23/internship-project:1.0.0
    restart: on-failure
    ports:
      - 8082:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=

    stdin_open: true
    tty: true

volumes:
  db:
